/**
 * Mapping of city names to their corresponding weather (.epw / .fwt) file names.
 */
export const CITY_EPW_MAP: Record<string, string> = {
  "ASHRAE CZ 1A": "2020_ASHRAE_1A_VERYHOT_HUMID.epw",
  "ASHRAE CZ 1B": "2020_ASHRAE_1B_VERYHOT_DRY.epw",
  "ASHRAE CZ 2A": "2020_ASHRAE_2A_HOT_HUMID.epw",
  "ASHRAE CZ 2B": "2020_ASHRAE_2B_HOT_DRY.epw",
  "ASHRAE CZ 3A": "2020_ASHRAE_3A_WARM_HUMID.epw",
  "ASHRAE CZ 3B": "2020_ASHRAE_3B_WARM_DRY.epw",
  "ASHRAE CZ 3C": "2020_ASHRAE_3C_WARM_MARINE.epw",
  "ASHRAE CZ 4A TMY": "2020_ASHRAE_4A_MIXED_HUMID.epw",
  "ASHRAE CZ 4B": "2020_ASHRAE_4B_MIXED_DRY.epw",
  "ASHRAE CZ 4C": "2020_ASHRAE_4C_MIXED_MARINE.epw",
  "ASHRAE CZ 5A": "2020_ASHRAE_5A_COOL_HUMID.epw",
  "ASHRAE CZ 5B": "2020_ASHRAE_5B_COOL_DRY.epw",
  "ASHRAE CZ 5C": "2020_ASHRAE_5C_COOL_MARINE.epw",
  "ASHRAE CZ 6A": "2020_ASHRAE_6A_COLD_HUMID.epw",
  "ASHRAE CZ 6B": "2020_ASHRAE_6B_COLD_DRY.epw",
  "ASHRAE CZ 7": "2020_ASHRAE_7_VERYCOLD.epw",
  "ASHRAE CZ 8": "2020_ASHRAE_8_SUBARCTIC.epw",
  "ASHRAE CZ 1A 2050": "2050_ASHRAE_1A_VERYHOT_HUMID.epw",
  "ASHRAE CZ 1B 2050": "2050_ASHRAE_1B_VERYHOT_DRY.epw",
  "ASHRAE CZ 2A 2050": "2050_ASHRAE_2A_HOT_HUMID.epw",
  "ASHRAE CZ 2B 2050": "2050_ASHRAE_2B_HOT_DRY.epw",
  "ASHRAE CZ 3A 2050": "2050_ASHRAE_3A_WARM_HUMID.epw",
  "ASHRAE CZ 3B 2050": "2050_ASHRAE_3B_WARM_DRY.epw",
  "ASHRAE CZ 3C 2050": "2050_ASHRAE_3C_WARM_MARINE.epw",
  "ASHRAE CZ 4A 2050": "2050_ASHRAE_4A_MIXED_HUMID.epw",
  "ASHRAE CZ 4B 2050": "2050_ASHRAE_4B_MIXED_DRY.epw",
  "ASHRAE CZ 4C 2050": "2050_ASHRAE_4C_MIXED_MARINE.epw",
  "ASHRAE CZ 5A 2050": "2050_ASHRAE_5A_COOL_HUMID.epw",
  "ASHRAE CZ 5B 2050": "2050_ASHRAE_5B_COOL_DRY.epw",
  "ASHRAE CZ 5C 2050": "2050_ASHRAE_5C_COOL_MARINE.epw",
  "ASHRAE CZ 6A 2050": "2050_ASHRAE_6A_COLD_HUMID.epw",
  "ASHRAE CZ 6B 2050": "2050_ASHRAE_6B_COLD_DRY.epw",
  "ASHRAE CZ 7 2050": "2050_ASHRAE_7_VERYCOLD.epw",
  "ASHRAE CZ 8 2050": "2050_ASHRAE_8_SUBARCTIC.epw",
  "ASHRAE CZ 1A 2080": "2080_ASHRAE_1A_VERYHOT_HUMID.epw",
  "ASHRAE CZ 1B 2080": "2080_ASHRAE_1B_VERYHOT_DRY.epw",
  "ASHRAE CZ 2A 2080": "2080_ASHRAE_2A_HOT_HUMID.epw",
  "ASHRAE CZ 2B 2080": "2080_ASHRAE_2B_HOT_DRY.epw",
  "ASHRAE CZ 3A 2080": "2080_ASHRAE_3A_WARM_HUMID.epw",
  "ASHRAE CZ 3B 2080": "2080_ASHRAE_3B_WARM_DRY.epw",
  "ASHRAE CZ 3C 2080": "2080_ASHRAE_3C_WARM_MARINE.epw",
  "ASHRAE CZ 4A 2080": "2080_ASHRAE_4A_MIXED_HUMID.epw",
  "ASHRAE CZ 4B 2080": "2080_ASHRAE_4B_MIXED_DRY.epw",
  "ASHRAE CZ 4C 2080": "2080_ASHRAE_4C_MIXED_MARINE.epw",
  "ASHRAE CZ 5A 2080": "2080_ASHRAE_5A_COOL_HUMID.epw",
  "ASHRAE CZ 5B 2080": "2080_ASHRAE_5B_COOL_DRY.epw",
  "ASHRAE CZ 5C 2080": "2080_ASHRAE_5C_COOL_MARINE.epw",
  "ASHRAE CZ 6A 2080": "2080_ASHRAE_6A_COLD_HUMID.epw",
  "ASHRAE CZ 6B 2080": "2080_ASHRAE_6B_COLD_DRY.epw",
  "ASHRAE CZ 7 2080": "2080_ASHRAE_7_VERYCOLD.epw",
  "ASHRAE CZ 8 2080": "2080_ASHRAE_8_SUBARCTIC.epw",
  "ALTURAS": "ALTURAS_725958_CZ2010.epw",
  "ARCATA AP": "ARCATA_725945_CZ2010.epw",
  "CANBERRA": "AUS_ACT_Canberra_949260_IWEC.epw",
  "Mascot Sydney Airport": "AUS_NSW_Mascot-Sydney.Airport_947670_RMY.epw",
  "BRISBANE": "AUS_QLD_Brisbane_945780_IWEC.epw",
  "MELBOURNE": "AUS_VIC_Melbourne_948660_IWEC.epw",
  "PERTH": "AUS_WA_Perth_946100_IWEC.epw",
  "Abbotsford BC CWEC": "Abbotsford_BC_CWEC.fwt",
  "AberdeenEWY": "AberdeenEWY.fwt",
  "AberporthEWY": "AberporthEWY.fwt",
  "AbuDhabiIWEC": "AbuDhabiIWEC.fwt",
  "AcapulcoIWEC": "AcapulcoIWEC.fwt",
  "AlbanyTMY2": "AlbanyTMY2.fwt",
  "AlbuquerqueTMY2": "AlbuquerqueTMY2.fwt",
  "AldergroveEWY": "AldergroveEWY.fwt",
  "AlgiersIWEC": "AlgiersIWEC.fwt",
  "AmarilloTMY2": "AmarilloTMY2.fwt",
  "AmsterdamIWEC": "AmsterdamIWEC.fwt",
  "AndravidaIWEC": "AndravidaIWEC.fwt",
  "AnkaraIWEC": "AnkaraIWEC.fwt",
  "AshevilleTMY2": "AshevilleTMY2.fwt",
  "AthensIWEC": "AthensIWEC.fwt",
  "AtlantaTMY2": "AtlantaTMY2.fwt",
  "Auckland71": "Auckland71.fwt",
  "AucklandIWEC": "AucklandIWEC.fwt",
  "BAKERSFIELD MEADOWS FIEL": "BAKERSFIELD_723840_CZ2010.epw",
  "BISHOP AP": "BISHOP_724800_CZ2010.epw",
  "BLUE CANYON AP": "BLUE-CANYON_725845_CZ2010.epw",
  "BLYTHE RIVERSIDE CO AP": "BLYTHE-RIVERSIDE-CO_747188_CZ2010.epw",
  "BURBANK GLENDALE PASADEN": "BURBANK-GLENDALE_722880_CZ2010.epw",
  "Baltimore TMY2": "Baltimore_TMY2.fwt",
  "BangkokIWEC": "BangkokIWEC.fwt",
  "BarcelonaIWEC": "BarcelonaIWEC.fwt",
  "Bari IGDG": "Bari_IGDG.fwt",
  "BarrowTMY2": "BarrowTMY2.fwt",
  "BeijingIWEC": "BeijingIWEC.fwt",
  "BergenIWEC": "BergenIWEC.fwt",
  "BerlinIWEC": "BerlinIWEC.fwt",
  "BirminghamEWY": "BirminghamEWY.fwt",
  "Boise TMY2": "Boise_TMY2.fwt",
  "BostonTMY2": "BostonTMY2.fwt",
  "BrindisiIWEC": "BrindisiIWEC.fwt",
  "Brisbane IWEC": "Brisbane_IWEC.fwt",
  "BristolEWY": "BristolEWY.fwt",
  "BrusselsIWEC": "BrusselsIWEC.fwt",
  "Burlington TMY2": "Burlington_TMY2.fwt",
  "CAMARILLO(AWOS)": "CAMARILLO_723926_CZ2010.epw",
  "CAMP PENDLETON MCAS": "CAMP-PENDLETON_722926_CZ2010.epw",
  "Kenora.AP": "CAN_ON_Kenora.AP.718500_TMYx.epw",
  "CARLSBAD MCCLELLAN": "CARLSBAD_722927_CZ2010.epw",
  "CA ARCATA AP": "CA_ARCATA-AP_725945_CZ2025.epw",
  "CA BLUE CANYON AP": "CA_BLUE-CANYON-AP_725845_CZ2025.epw",
  "CA BURBANK GLNDLE PASAD": "CA_BURBANK-GLNDLE-PASAD-AP_722880S_CZ2022.epw",
  "CA BURBANK GLNDLE PASAD AP": "CA_BURBANK-GLNDLE-PASAD-AP_722880_CZ2025.epw",
  "CA FRESNO YOSEMITE IAP": "CA_FRESNO-YOSEMITE-IAP_723890_CZ2025.epw",
  "CA FULLERTON MUNI AP": "CA_FULLERTON-MUNI-AP_722976_CZ2025.epw",
  "CA LOS ANGELES IAP": "CA_LOS-ANGELES-IAP_722950_CZ2025.epw",
  "CA OAKLAND METRO AP": "CA_OAKLAND-METRO-AP_724930_CZ2025.epw",
  "CA PALM SPRINGS IAP": "CA_PALM-SPRINGS-IAP_722868_CZ2025.epw",
  "CA PALMDALE AP": "CA_PALMDALE-AP_723820_CZ2025.epw",
  "CA PASO ROBLES MUNI AP": "CA_PASO-ROBLES-MUNI-AP_723965_CZ2025.epw",
  "CA RED BLUFF MUNI AP": "CA_RED-BLUFF-MUNI-AP_725910_CZ2025.epw",
  "CA RIVERSIDE MUNI": "CA_RIVERSIDE-MUNI_722869_CZ2025.epw",
  "CA SACRAMENTO EXECUTIVE": "CA_SACRAMENTO-EXECUTIVE-AP_724830S_CZ2022.epw",
  "CA SACRAMENTO EXECUTIVE AP": "CA_SACRAMENTO-EXECUTIVE-AP_724830_CZ2025.epw",
  "CA SAN DIEGO LINDBERGH FIE": "CA_SAN-DIEGO-LINDBERGH-FIELD_722900_CZ2025.epw",
  "CA SAN DIEGO LINDBERGH F": "CA_SAN-DIEGO-LINDBERGH-FLD_722900S_CZ2022.epw",
  "CA SAN JOSE REID HILLV": "CA_SAN-JOSE-REID-HILLV_724946S_CZ2022.epw",
  "CA SANTA MARIA PUBLIC AP": "CA_SANTA-MARIA-PUBLIC-AP_723940_CZ2025.epw",
  "CA SANTA ROSA(AWOS)": "CA_SANTA-ROSA-AP_724957S_CZ2022.epw",
  "CA TORRANCE MUNI AP": "CA_TORRANCE-MUNI-AP_722955S_CZ2022.epw",
  "CHINA LAKE NAF": "CHINA-LAKE_746120_CZ2010.epw",
  "CHINO AP": "CHINO_722899_CZ2010.epw",
  "HONG KONG": "CHN_Hong_Kong_SAR_450070_CityUHK.epw",
  "CONCORD BUCHANAN FIELD": "CONCORD_724936_CZ2010.epw",
  "CRESCENT CITY FAA AP": "CRESCENT-CITY_725946_CZ2010.epw",
  "CairoIWEC": "CairoIWEC.fwt",
  "Calgary AB CWEC": "Calgary_AB_CWEC.fwt",
  "CamborneEWY": "CamborneEWY.fwt",
  "Cape Town 19": "CapeTownDOE2.epw",
  "CaribouTMY2": "CaribouTMY2.fwt",
  "ChicagoMidwayTMY": "ChicagoMidwayTMY.fwt",
  "ChicagoOHareTMY2": "ChicagoOHareTMY2.fwt",
  "ClevelandTMY2": "ClevelandTMY2.fwt",
  "ColumbusTMY2": "ColumbusTMY2.fwt",
  "CopenhagenIWEC": "CopenhagenIWEC.fwt",
  "CutBankTMY2": "CutBankTMY2.fwt",
  "DAGGETT BARSTOW DAGGETT": "DAGGETT-BARSTOW_723815_CZ2010.epw",
  "DamascusIWEC": "DamascusIWEC.fwt",
  "DaytonTMY2": "DaytonTMY2.fwt",
  "DenverStapletonTMY": "DenverStapletonTMY.fwt",
  "DetroitTMY": "DetroitTMY.fwt",
  "Dublin89": "Dublin89.fwt",
  "DublinIWEC": "DublinIWEC.fwt",
  "DuluthTMY2": "DuluthTMY2.fwt",
  "DundeeEWY": "DundeeEWY.fwt",
  "Durban 19": "DurbanDOE2.epw",
  "EDWARDS AFB": "EDWARDS-AFB_723810_CZ2010.epw",
  "EL CENTRO NAF": "EL-CENTRO_722810_CZ2010.epw",
  "EUREKA": "EUREKA_725940_CZ2010.epw",
  "Edmonton AB CWEC": "Edmonton_AB_CWEC.fwt",
  "EriePA TRY2": "EriePA_TRY2.fwt",
  "EskdalemuirEWY": "EskdalemuirEWY.fwt",
  "EvansvilleTMY2": "EvansvilleTMY2.fwt",
  "TRAVIS FLD AFB": "FAIRFLD-TRAVIS-AFB_745160_CZ2010.epw",
  "LYON": "FRA_Lyon_074810_IWEC.epw",
  "NANTES": "FRA_Nantes_072220_IWEC.epw",
  "FRESNO YOSEMITE IAP": "FRESNO_723890_CZ2010.epw",
  "FULLERTON MUNICIPAL": "FULLERTON_722976_CZ2010.epw",
  "Fairbanks TMY2": "Fairbanks_TMY2.fwt",
  "FargoTMY2": "FargoTMY2.fwt",
  "FlagstaffTMY2": "FlagstaffTMY2.fwt",
  "FortWorthTMY2": "FortWorthTMY2.fwt",
  "FresnoTMY2": "FresnoTMY2.fwt",
  "Gibraltar.Intl.AP": "Gibraltar_TRY.epw",
  "Gioia del Colle IGDG": "Gioia_del_Colle_IGDG.fwt",
  "GlasgowEWY": "GlasgowEWY.fwt",
  "GrandRapidsTMY2": "GrandRapidsTMY2.fwt",
  "GrazIWEC": "GrazIWEC.fwt",
  "GuangzhouIWEC": "GuangzhouIWEC.fwt",
  "JACK NORTHROP FLD H": "HAWTHORNE-NORTHROP-FLD_722956_CZ2010.epw",
  "HAYWARD AIR TERM": "HAYWARD_724935_CZ2010.epw",
  "HanoiIWEC": "HanoiIWEC.fwt",
  "HarbinIWEC": "HarbinIWEC.fwt",
  "HeathrowEWY": "HeathrowEWY.fwt",
  "Helena TMY2": "Helena_TMY2.fwt",
  "HelsinkiIWEC": "HelsinkiIWEC.fwt",
  "HoustonTMY2": "HoustonTMY2.fwt",
  "Hrow9697": "Hrow9697.fwt",
  "IMPERIAL BEACH REAM FIEL": "IMPERIAL-BEACH_722909_CZ2010.epw",
  "IMPERIAL": "IMPERIAL_747185_CZ2010.epw",
  "Bangalore": "IND_Bangalore_432950_ISHRAE.epw",
  "CHENNAI": "IND_Chennai_432790_IWEC.epw",
  "NEW DELHI": "IND_New_Delhi_421820_IWEC.epw",
  "INYOKERN": "INYOKERN_723826_CZ2010.epw",
  "InnsbruckIWEC": "InnsbruckIWEC.fwt",
  "Istanbul IWEC": "Istanbul_IWEC.fwt",
  "Jerusalem IWEC": "Jerusalem_IWEC.fwt",
  "Johannesburg/Jan 19": "JohannesburgDOE2.epw",
  "JohannesburgIWEC": "JohannesburgIWEC.fwt",
  "Juneau TMY": "Juneau_TMY.fwt",
  "KagoshimaIWEC": "KagoshimaIWEC.fwt",
  "Kamloops BC CWEC": "Kamloops_BC_CWEC.fwt",
  "KansasCityTMY2": "KansasCityTMY2.fwt",
  "Kew67": "Kew67.fwt",
  "KewEWY": "KewEWY.fwt",
  "KolkataIWEC": "KolkataIWEC.fwt",
  "KualaLumpurIWEC": "KualaLumpurIWEC.fwt",
  "KuchingIWEC": "KuchingIWEC.fwt",
  "KunmingIWEC": "KunmingIWEC.fwt",
  "Kuwait KISR": "Kuwait_KISR.fwt",
  "LANCASTER GEN WM FOX FIE": "LANCASTER_723816_CZ2010.epw",
  "LEMOORE REEVES NAS": "LEMOORE_747020_CZ2010.epw",
  "LIVERMORE MUNICIPAL": "LIVERMORE_724927_CZ2010.epw",
  "LOMPOC(AWOS)": "LOMPOC_722895_CZ2010.epw",
  "LONG BEACH DAUGHERTY FLD": "LONG-BEACH_722970_CZ2010.epw",
  "LOS ALAMITOS AAF": "LOS-ALAMITOS_722975_CZ2010.epw",
  "LOS ANGELES DOWNTOWN USC": "LOS-ANGELES-DOWNTOWN_722874_CZ2010.epw",
  "LOS ANGELES IAP": "LOS-ANGELES-INTL_722950_CZ2010.epw",
  "LanzhouIWEC": "LanzhouIWEC.fwt",
  "LaredoTMY": "LaredoTMY.fwt",
  "LarnacaWYEC": "LarnacaWYEC.fwt",
  "LasVegasTMY2": "LasVegasTMY2.fwt",
  "LewistownTMY2": "LewistownTMY2.fwt",
  "LittleRockTMY2": "LittleRockTMY2.fwt",
  "LosAngelesTMY2": "LosAngelesTMY2.fwt",
  "LouisvilleTMY2": "LouisvilleTMY2.fwt",
  "LynchburgTMY2": "LynchburgTMY2.fwt",
  "BEALE AFB": "MARYSVILLE-BEALE-AFB_724837_CZ2010.epw",
  "MB WINNIPEG IAP": "MB_WINNIPEG-IAP_718520S_16.epw",
  "MERCED MUNI MACREADY": "MERCED_724815_CZ2010.epw",
  "MODESTO CITY CO AP": "MODESTO_724926_CZ2010.epw",
  "MOJAVE": "MOJAVE_722953_CZ2010.epw",
  "MONTAGUE SISKIYOU CO AP": "MONTAGUE-SISKIYOU-CO_725955_CZ2010.epw",
  "MONTEREY NAF": "MONTEREY_724915_CZ2010.epw",
  "MOUNT SHASTA": "MOUNT-SHASTA_725957_CZ2010.epw",
  "MacauIWEC": "MacauIWEC.fwt",
  "MadisonTMY2": "MadisonTMY2.fwt",
  "MadridIWEC": "MadridIWEC.fwt",
  "ManchesterEWY": "ManchesterEWY.fwt",
  "MarseilleIWEC": "MarseilleIWEC.fwt",
  "MatsumotoIWEC": "MatsumotoIWEC.fwt",
  "MelbourneIWEC": "MelbourneIWEC.fwt",
  "Memphis TMY2": "Memphis_TMY2.fwt",
  "MessinaIWEC": "MessinaIWEC.fwt",
  "MexicoCityIWEC": "MexicoCityIWEC.fwt",
  "MiamiTMY2": "MiamiTMY2.fwt",
  "MilanIWEC": "MilanIWEC.fwt",
  "Minneapolis TMY2": "Minneapolis_TMY2.fwt",
  "Montreal QC CWEC": "Montreal_QC_CWEC.fwt",
  "MumbaiIWEC": "MumbaiIWEC.fwt",
  "Beitbridge 19": "MusinaDOE2.epw",
  "MuskegonTMY2": "MuskegonTMY2.fwt",
  "M\u00fcnchenIWEC": "M\u00fcnchenIWEC.fwt",
  "NAPA CO": "NAPA-CO_724955_CZ2010.epw",
  "NEEDLES AP": "NEEDLES_723805_CZ2010.epw",
  "Auckland": "NZL_Auckland_Auckland_AK_931190_NIWA.epw",
  "Rotorua": "NZL_Bay_of_Plenty_Rotorua_RR_932470_NIWA.epw",
  "Tauranga": "NZL_Bay_of_Plenty_Tauranga_BP_931850_NIWA.epw",
  "Christchurch": "NZL_Canterbury_Christchurch_CC_937800_NIWA.epw",
  "Lauder": "NZL_Central_Otago_Lauder_OC_938510_NIWA.epw",
  "Napier": "NZL_Hawkes_Bay_Napier_EC_933730_NIWA.epw",
  "Paraparaumu": "NZL_Manawatu_Paraparaumu_MW_934200_NIWA.epw",
  "Nelson": "NZL_Nelson_Marlborough_Nelson_NM_935460_NIWA.epw",
  "Kaitaia": "NZL_Northland_Kaitaia_NL_930120_NIWA.epw",
  "Dunedin": "NZL_Otago_Dunedin_DN_938910_NIWA.epw",
  "Queenstown": "NZL_Queenstown_Lakes_Qnstwn_QL_938310_NIWA.epw",
  "Invercargill": "NZL_Southland_Invercargill_IN_938450_NIWA.epw",
  "New Plymouth": "NZL_Taranaki_New_Plymouth_NP_933090_NIWA.epw",
  "Turangi": "NZL_Taupo_Turangi_TP_932450_NIWA.epw",
  "Hamilton": "NZL_Waikato_Hamilton_HN_931730_NIWA.epw",
  "Masterton": "NZL_Wairarapa_Masterton_WI_934710_NIWA.epw",
  "Wellington": "NZL_Wellington_Wellington_WN_934360_NIWA.epw",
  "Hokitika": "NZL_West_Coast_Hokitika_WC_936150_NIWA.epw",
  "NadiIWEC": "NadiIWEC.fwt",
  "NagoyaIWEC": "NagoyaIWEC.fwt",
  "NancyIWEC": "NancyIWEC.fwt",
  "Nanjing CSWD": "Nanjing_CSWD.fwt",
  "Nanjing CTYW": "Nanjing_CTYW.fwt",
  "NaplesIWEC": "NaplesIWEC.fwt",
  "Nashville TMY2": "Nashville_TMY2.fwt",
  "NewYorkTMY2": "NewYorkTMY2.fwt",
  "NewcastleEWY": "NewcastleEWY.fwt",
  "NorfolkTMY2": "NorfolkTMY2.fwt",
  "NorthBendTMY2": "NorthBendTMY2.fwt",
  "NorwichEWY": "NorwichEWY.fwt",
  "OAKLAND METRO AP": "OAKLAND_724930_CZ2010.epw",
  "OXNARD AP": "OXNARD_723927_CZ2010.epw",
  "OostendeIWEC": "OostendeIWEC.fwt",
  "OsakaIWEC": "OsakaIWEC.fwt",
  "OsloIWEC": "OsloIWEC.fwt",
  "Ottawa ON CWEC": "Ottawa_ON_CWEC.fwt",
  "PALM SPRINGS IAP": "PALM-SPRINGS-INTL_722868_CZ2010.epw",
  "PALM SPRINGS THERMAL AP": "PALM-SPRINGS-THERMAL_747187_CZ2010.epw",
  "PALMDALE AP": "PALMDALE_723820_CZ2010.epw",
  "PALO ALTO AP": "PALO-ALTO_724937_CZ2010.epw",
  "PASO ROBLES MUNI AP": "PASO-ROBLES_723965_CZ2010.epw",
  "MANILA": "PHL_Manila_984290_IWEC.epw",
  "POINT MUGU NF": "POINT-MUGU_723910_CZ2010.epw",
  "PORTERVILLE(AWOS)": "PORTERVILLE_723895_CZ2010.epw",
  "PalermoIWEC": "PalermoIWEC.fwt",
  "PalmBeachTMY2": "PalmBeachTMY2.fwt",
  "PalmaIWEC": "PalmaIWEC.fwt",
  "ParisOrlyIWEC": "ParisOrlyIWEC.fwt",
  "PhiladelphiaTMY2": "PhiladelphiaTMY2.fwt",
  "PhoenixTMY2": "PhoenixTMY2.fwt",
  "PisaIWEC": "PisaIWEC.fwt",
  "PocatelloTMY2": "PocatelloTMY2.fwt",
  "PortHedlandIWEC": "PortHedlandIWEC.fwt",
  "PortlandTM2": "PortlandTM2.fwt",
  "PortoIWEC": "PortoIWEC.fwt",
  "Potenza IGDG": "Potenza_IGDG.fwt",
  "PragueWYEC": "PragueWYEC.fwt",
  "Pretoria Forum 19": "PretoriaDOE2.epw",
  "ProvidenceTMY2": "ProvidenceTMY2.fwt",
  "RED BLUFF MUNI AP": "RED-BLUFF_725910_CZ2010.epw",
  "REDDING MUNI AP": "REDDING_725920_CZ2010.epw",
  "MARCH AFB": "RIVERSIDE-MARCH-AFB_722860_CZ2010.epw",
  "RIVERSIDE MUNI": "RIVERSIDE_722869_CZ2010.epw",
  "RaleighTM2": "RaleighTM2.fwt",
  "Rockford TMY2": "Rockford_TMY2.fwt",
  "RomeIWEC": "RomeIWEC.fwt",
  "SACRAMENTO EXECUTIVE AP": "SACRAMENTO-EXECUTIVE_724830_CZ2010.epw",
  "SACRAMENTO METRO AP": "SACRAMENTO-METRO_724839_CZ2010.epw",
  "SALINAS MUNI AP": "SALINAS_724917_CZ2010.epw",
  "SAN CARLOS AP": "SAN-CARLOS_724938_CZ2010.epw",
  "SAN CLEMENTE IS NAAS": "SAN-CLEMENTE-IS_722925_CZ2010.epw",
  "SAN DIEGO GILLESPIE": "SAN-DIEGO-GILLESPIE_722907_CZ2010.epw",
  "SAN DIEGO LINDBERGH FIEL": "SAN-DIEGO-LINDBERGH_722900_CZ2010.epw",
  "SAN DIEGO MONTGOMER": "SAN-DIEGO-MONTGOMER_722903_CZ2010.epw",
  "SAN DIEGO NORTH ISLAND N": "SAN-DIEGO-NORTH-IS_722906_CZ2010.epw",
  "SAN FRANCISCO IAP": "SAN-FRANCISCO-INTL_724940_CZ2010.epw",
  "SAN JOSE IAP": "SAN-JOSE-INTL_724945_CZ2010.epw",
  "SAN JOSE REID HILLV": "SAN-JOSE-REID_724946_CZ2010.epw",
  "SAN LUIS CO RGNL": "SAN-LUIS-CO_722897_CZ2010.epw",
  "SAN NICHOLAS ISLAND": "SAN-NICHOLAS-IS_722910_CZ2010.epw",
  "SANDBERG": "SANDBERG_723830_CZ2010.epw",
  "SANTA ANA JOHN WAYNE AP": "SANTA-ANA_722977_CZ2010.epw",
  "SANTA BARBARA MUNI AP": "SANTA-BARBARA_723925_CZ2010.epw",
  "SANTA MARIA PUBLIC AP": "SANTA-MARIA_723940_CZ2010.epw",
  "SANTA MONICA MUNI": "SANTA-MONICA_722885_CZ2010.epw",
  "SANTA ROSA(AWOS)": "SANTA-ROSA_724957_CZ2010.epw",
  "LAKE TAHOE": "SOUTH-LAKE-TAHOE_725847_CZ2010.epw",
  "STOCKTON METRO AP": "STOCKTON_724920_CZ2010.epw",
  "Salem TMY2": "Salem_TMY2.fwt",
  "SaltLakeCityTMY2": "SaltLakeCityTMY2.fwt",
  "SanDiegoTMY2": "SanDiegoTMY2.fwt",
  "SanFranciscoTMY2": "SanFranciscoTMY2.fwt",
  "SanJuanTMY2": "SanJuanTMY2.fwt",
  "SantanderIWEC": "SantanderIWEC.fwt",
  "SapporoIWEC": "SapporoIWEC.fwt",
  "Saskatoon SK CWEC": "Saskatoon_SK_CWEC.fwt",
  "ScottsbluffTMY2": "ScottsbluffTMY2.fwt",
  "SeattleTMY2": "SeattleTMY2.fwt",
  "SevillaIWEC": "SevillaIWEC.fwt",
  "ShanghaiIWEC": "ShanghaiIWEC.fwt",
  "SheffieldEWY": "SheffieldEWY.fwt",
  "ShenyangIWEC": "ShenyangIWEC.fwt",
  "SheridanTMY2": "SheridanTMY2.fwt",
  "ShimonosekiIWEC": "ShimonosekiIWEC.fwt",
  "SingaporeIWEC": "SingaporeIWEC.fwt",
  "SiouxFallsTMY2": "SiouxFallsTMY2.fwt",
  "Smithers BC CWEC": "Smithers_BC_CWEC.fwt",
  "SpokaneTMY2": "SpokaneTMY2.fwt",
  "SpringfieldTMY2": "SpringfieldTMY2.fwt",
  "StHubertIWEC": "StHubertIWEC.fwt",
  "StPetersburg IWEC": "StPetersburg_IWEC.fwt",
  "StockholmIWEC": "StockholmIWEC.fwt",
  "Summerland BC CWEC": "Summerland_BC_CWEC.fwt",
  "SydneyIWEC": "SydneyIWEC.fwt",
  "TORRANCE MUNI AP": "TORRANCE_722955_CZ2010.epw",
  "TRUCKEE TAHOE": "TRUCKEE-TAHOE_725846_CZ2010.epw",
  "TWENTYNINE PALMS": "TWENTYNINE-PALMS_690150_CZ2010.epw",
  "TaipeiIWEC": "TaipeiIWEC.fwt",
  "TallahasseeTMY2": "TallahasseeTMY2.fwt",
  "TampaTMY2": "TampaTMY2.fwt",
  "Taranto IGDG": "Taranto_IGDG.fwt",
  "ThessalonikiIWEC": "ThessalonikiIWEC.fwt",
  "TokyoHyakuriIWEC": "TokyoHyakuriIWEC.fwt",
  "TopekaTMY2": "TopekaTMY2.fwt",
  "TorinoIWEC": "TorinoIWEC.fwt",
  "Toronto ON CWEC": "Toronto_ON_CWEC.fwt",
  "TosashimizuIWEC": "TosashimizuIWEC.fwt",
  "TraverseCity TMY2": "TraverseCity_TMY2.fwt",
  "TripoliIWEC": "TripoliIWEC.fwt",
  "TulsaTMY2": "TulsaTMY2.fwt",
  "UKIAH MUNI AP": "UKIAH_725905_CZ2010.epw",
  "Denver Intl Ap": "USA_CO_Denver_Intl_AP_725650_TMY3.epw",
  "Atlanta Hartsfield Intl Ap": "USA_GA_Atlanta-Hartsfield-Jackson_Intl.AP_722190_TMY3.epw",
  "Chicago Ohare Intl Ap": "USA_IL_Chicago-OHare_Intl_AP_725300_TMY3.epw",
  "New York Central Prk Obs Belv": "USA_NY_New_York-Central_Park_725033_TMY3.epw",
  "Bellingham Intl Ap": "USA_WA_Bellingham.Intl.AP.727976_TMY3.epw",
  "Upington 19": "UpingtonDOE2.epw",
  "UrumqiIWEC": "UrumqiIWEC.fwt",
  "VAN NUYS AP": "VAN-NUYS_722886_CZ2010.epw",
  "VANDENBERG AFB": "VANDENBERG-AFB_723930_CZ2010.epw",
  "VISALIA MUNI(AWOS)": "VISALIA_723896_CZ2010.epw",
  "ValenciaIWEC": "ValenciaIWEC.fwt",
  "Vancouver BC CWEC": "Vancouver_BC_CWEC.fwt",
  "VeniceIWEC": "VeniceIWEC.fwt",
  "VeracruzIWEC": "VeracruzIWEC.fwt",
  "VicenzaIGDG": "VicenzaIGDG.fwt",
  "Victoria BC CWEC": "Victoria_BC_CWEC.fwt",
  "WarsawIWEC": "WarsawIWEC.fwt",
  "WashingtonTMY2": "WashingtonTMY2.fwt",
  "WellingtonIWEC": "WellingtonIWEC.fwt",
  "Winnipeg MB CWEC": "Winnipeg_MB_CWEC.fwt",
  "YUBA CO": "YUBA-CO_724838_CZ2010.epw"
};

export function getEpwFilename(cityName: string): string {
  if (!cityName) return "";
  if (CITY_EPW_MAP[cityName]) return CITY_EPW_MAP[cityName];
  if (cityName.endsWith(".epw") || cityName.endsWith(".fwt")) return cityName;
  const sanitized = cityName.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase();
  return `${sanitized}_WEATHER.epw`;
}
