/**
 * Hierarchical region -> country -> province/state -> city mapping.
 */
export const REGION_DATA: Record<string, Record<string, Record<string, string[]>>> = {
  "Existing Regions": {
    "Global Cities": {
      "Built in": [
        "Amsterdam",
        "Atlanta",
        "Auckland",
        "Bangkok",
        "Beijing",
        "Birmingham",
        "Bombay",
        "Boston",
        "Brandon",
        "Brisbane",
        "Budapest",
        "Calgary",
        "Cambridge",
        "Cardiff",
        "Chennai",
        "Chicago",
        "Christchurch",
        "Coimbatore",
        "Dallas",
        "Dawson City",
        "Denver",
        "Edinburgh",
        "Edmonton",
        "Gillam",
        "Glasgow",
        "Halifax",
        "Hamilton",
        "Hanoi",
        "Hong Kong",
        "Houston",
        "Indianapolis",
        "Jakarta",
        "Kamloops",
        "Kanpur",
        "Karachi",
        "Kelowna",
        "Kenora",
        "Kyoto",
        "Las Vegas",
        "Lethbridge",
        "Liverpool",
        "London",
        "Los Angeles",
        "Lucknow",
        "Madurai",
        "Manila",
        "Melbourne",
        "Miami",
        "Montreal",
        "Moscow",
        "Nagpur",
        "New Delhi",
        "New York",
        "Norway House",
        "Nottingham",
        "Orlando",
        "Osaka",
        "Oshawa",
        "Ottawa",
        "Paris",
        "Perth",
        "Phoenix",
        "Pune",
        "Quebec City",
        "Red Deer",
        "Red Earth",
        "Regina",
        "Rome",
        "San Diego",
        "San Francisco",
        "Saskatoon",
        "Seattle",
        "Shanghai",
        "Shenzhen",
        "Taipei",
        "Thompson",
        "Thunder Bay",
        "Toronto",
        "Vancouver",
        "Varanasi",
        "Victoria",
        "Washington DC",
        "Whitehorse",
        "Winnipeg",
        "ASHRAE CZ 1A",
        "ASHRAE CZ 1B",
        "ASHRAE CZ 2A",
        "ASHRAE CZ 2B",
        "ASHRAE CZ 3A",
        "ASHRAE CZ 3B",
        "ASHRAE CZ 3C",
        "ASHRAE CZ 4A TMY",
        "ASHRAE CZ 4B",
        "ASHRAE CZ 4C",
        "ASHRAE CZ 5A",
        "ASHRAE CZ 5B",
        "ASHRAE CZ 5C",
        "ASHRAE CZ 6A",
        "ASHRAE CZ 6B",
        "ASHRAE CZ 7",
        "ASHRAE CZ 8",
        "ASHRAE CZ 1A 2050",
        "ASHRAE CZ 1B 2050",
        "ASHRAE CZ 2A 2050",
        "ASHRAE CZ 2B 2050",
        "ASHRAE CZ 3A 2050",
        "ASHRAE CZ 3B 2050",
        "ASHRAE CZ 3C 2050",
        "ASHRAE CZ 4A 2050",
        "ASHRAE CZ 4B 2050",
        "ASHRAE CZ 4C 2050",
        "ASHRAE CZ 5A 2050",
        "ASHRAE CZ 5B 2050",
        "ASHRAE CZ 5C 2050",
        "ASHRAE CZ 6A 2050",
        "ASHRAE CZ 6B 2050",
        "ASHRAE CZ 7 2050",
        "ASHRAE CZ 8 2050",
        "ASHRAE CZ 1A 2080",
        "ASHRAE CZ 1B 2080",
        "ASHRAE CZ 2A 2080",
        "ASHRAE CZ 2B 2080",
        "ASHRAE CZ 3A 2080",
        "ASHRAE CZ 3B 2080",
        "ASHRAE CZ 3C 2080",
        "ASHRAE CZ 4A 2080",
        "ASHRAE CZ 4B 2080",
        "ASHRAE CZ 4C 2080",
        "ASHRAE CZ 5A 2080",
        "ASHRAE CZ 5B 2080",
        "ASHRAE CZ 5C 2080",
        "ASHRAE CZ 6A 2080",
        "ASHRAE CZ 6B 2080",
        "ASHRAE CZ 7 2080",
        "ASHRAE CZ 8 2080",
        "ALTURAS",
        "ARCATA AP",
        "CANBERRA",
        "Mascot Sydney Airport",
        "BRISBANE",
        "MELBOURNE",
        "PERTH",
        "Abbotsford BC CWEC",
        "AberdeenEWY",
        "AberporthEWY",
        "AbuDhabiIWEC",
        "AcapulcoIWEC",
        "AlbanyTMY2",
        "AlbuquerqueTMY2",
        "AldergroveEWY",
        "AlgiersIWEC",
        "AmarilloTMY2",
        "AmsterdamIWEC",
        "AndravidaIWEC",
        "AnkaraIWEC",
        "AshevilleTMY2",
        "AthensIWEC",
        "AtlantaTMY2",
        "Auckland71",
        "AucklandIWEC",
        "BAKERSFIELD MEADOWS FIEL",
        "BISHOP AP",
        "BLUE CANYON AP",
        "BLYTHE RIVERSIDE CO AP",
        "BURBANK GLENDALE PASADEN",
        "Baltimore TMY2",
        "BangkokIWEC",
        "BarcelonaIWEC",
        "Bari IGDG",
        "BarrowTMY2",
        "BeijingIWEC",
        "BergenIWEC",
        "BerlinIWEC",
        "BirminghamEWY",
        "Boise TMY2",
        "BostonTMY2",
        "BrindisiIWEC",
        "Brisbane IWEC",
        "BristolEWY",
        "BrusselsIWEC",
        "Burlington TMY2",
        "CAMARILLO(AWOS)",
        "CAMP PENDLETON MCAS",
        "Kenora.AP",
        "CARLSBAD MCCLELLAN",
        "CA ARCATA AP",
        "CA ARCATA AP (CA_ARCATA-AP_725945_CZ2025.epw)",
        "CA BLUE CANYON AP",
        "CA BLUE CANYON AP (CA_BLUE-CANYON-AP_725845_CZ2025.epw)",
        "CA BURBANK GLNDLE PASAD",
        "CA BURBANK GLNDLE PASAD AP",
        "CA FRESNO YOSEMITE IAP",
        "CA FRESNO YOSEMITE IAP (CA_FRESNO-YOSEMITE-IAP_723890_CZ2025.epw)",
        "CA FULLERTON MUNI AP",
        "CA FULLERTON MUNI AP (CA_FULLERTON-MUNI-AP_722976_CZ2025.epw)",
        "CA LOS ANGELES IAP",
        "CA OAKLAND METRO AP",
        "CA OAKLAND METRO AP (CA_OAKLAND-METRO-AP_724930_CZ2025.epw)",
        "CA PALM SPRINGS IAP",
        "CA PALM SPRINGS IAP (CA_PALM-SPRINGS-IAP_722868_CZ2025.epw)",
        "CA PALMDALE AP",
        "CA PALMDALE AP (CA_PALMDALE-AP_723820_CZ2025.epw)",
        "CA PASO ROBLES MUNI AP",
        "CA RED BLUFF MUNI AP",
        "CA RED BLUFF MUNI AP (CA_RED-BLUFF-MUNI-AP_725910_CZ2025.epw)",
        "CA RIVERSIDE MUNI",
        "CA RIVERSIDE MUNI (CA_RIVERSIDE-MUNI_722869_CZ2025.epw)",
        "CA SACRAMENTO EXECUTIVE",
        "CA SACRAMENTO EXECUTIVE AP",
        "CA SAN DIEGO LINDBERGH FIE",
        "CA SAN DIEGO LINDBERGH F",
        "CA SAN JOSE REID HILLV",
        "CA SANTA MARIA PUBLIC AP",
        "CA SANTA MARIA PUBLIC AP (CA_SANTA-MARIA-PUBLIC-AP_723940_CZ2025.epw)",
        "CA SANTA ROSA(AWOS)",
        "CA SANTA ROSA(AWOS) (CA_SANTA-ROSA-AP_724957S_CZ2022.epw)",
        "CA TORRANCE MUNI AP",
        "CHINA LAKE NAF",
        "CHINO AP",
        "HONG KONG",
        "CONCORD BUCHANAN FIELD",
        "CRESCENT CITY FAA AP",
        "CairoIWEC",
        "Calgary AB CWEC",
        "CamborneEWY",
        "Cape Town 19",
        "CaribouTMY2",
        "ChicagoMidwayTMY",
        "ChicagoOHareTMY2",
        "ClevelandTMY2",
        "ColumbusTMY2",
        "CopenhagenIWEC",
        "CutBankTMY2",
        "DAGGETT BARSTOW DAGGETT",
        "DamascusIWEC",
        "DaytonTMY2",
        "DenverStapletonTMY",
        "DetroitTMY",
        "Dublin89",
        "DublinIWEC",
        "DuluthTMY2",
        "DundeeEWY",
        "Durban 19",
        "EDWARDS AFB",
        "EL CENTRO NAF",
        "EUREKA",
        "Edmonton AB CWEC",
        "EriePA TRY2",
        "EskdalemuirEWY",
        "EvansvilleTMY2",
        "TRAVIS FLD AFB",
        "LYON",
        "NANTES",
        "FRESNO YOSEMITE IAP",
        "FULLERTON MUNICIPAL",
        "Fairbanks TMY2",
        "FargoTMY2",
        "FlagstaffTMY2",
        "FortWorthTMY2",
        "FresnoTMY2",
        "Gibraltar.Intl.AP",
        "Gioia del Colle IGDG",
        "GlasgowEWY",
        "GrandRapidsTMY2",
        "GrazIWEC",
        "GuangzhouIWEC",
        "JACK NORTHROP FLD H",
        "HAYWARD AIR TERM",
        "HanoiIWEC",
        "HarbinIWEC",
        "HeathrowEWY",
        "Helena TMY2",
        "HelsinkiIWEC",
        "HoustonTMY2",
        "Hrow9697",
        "IMPERIAL BEACH REAM FIEL",
        "IMPERIAL",
        "Bangalore",
        "CHENNAI",
        "NEW DELHI",
        "INYOKERN",
        "InnsbruckIWEC",
        "Istanbul IWEC",
        "Jerusalem IWEC",
        "Johannesburg/Jan 19",
        "JohannesburgIWEC",
        "Juneau TMY",
        "KagoshimaIWEC",
        "Kamloops BC CWEC",
        "KansasCityTMY2",
        "Kew67",
        "KewEWY",
        "KolkataIWEC",
        "KualaLumpurIWEC",
        "KuchingIWEC",
        "KunmingIWEC",
        "Kuwait KISR",
        "LANCASTER GEN WM FOX FIE",
        "LEMOORE REEVES NAS",
        "LIVERMORE MUNICIPAL",
        "LOMPOC(AWOS)",
        "LONG BEACH DAUGHERTY FLD",
        "LOS ALAMITOS AAF",
        "LOS ANGELES DOWNTOWN USC",
        "LOS ANGELES IAP",
        "LanzhouIWEC",
        "LaredoTMY",
        "LarnacaWYEC",
        "LasVegasTMY2",
        "LewistownTMY2",
        "LittleRockTMY2",
        "LosAngelesTMY2",
        "LouisvilleTMY2",
        "LynchburgTMY2",
        "BEALE AFB",
        "MB WINNIPEG IAP",
        "MERCED MUNI MACREADY",
        "MODESTO CITY CO AP",
        "MOJAVE",
        "MONTAGUE SISKIYOU CO AP",
        "MONTEREY NAF",
        "MOUNT SHASTA",
        "MacauIWEC",
        "MadisonTMY2",
        "MadridIWEC",
        "ManchesterEWY",
        "MarseilleIWEC",
        "MatsumotoIWEC",
        "MelbourneIWEC",
        "Memphis TMY2",
        "MessinaIWEC",
        "MexicoCityIWEC",
        "MiamiTMY2",
        "MilanIWEC",
        "Minneapolis TMY2",
        "Montreal QC CWEC",
        "MumbaiIWEC",
        "Beitbridge 19",
        "MuskegonTMY2",
        "M\u00fcnchenIWEC",
        "NAPA CO",
        "NEEDLES AP",
        "Rotorua",
        "Tauranga",
        "Lauder",
        "Napier",
        "Paraparaumu",
        "Nelson",
        "Kaitaia",
        "Dunedin",
        "Queenstown",
        "Invercargill",
        "New Plymouth",
        "Turangi",
        "Masterton",
        "Wellington",
        "Hokitika",
        "NadiIWEC",
        "NagoyaIWEC",
        "NancyIWEC",
        "Nanjing CSWD",
        "Nanjing CTYW",
        "NaplesIWEC",
        "Nashville TMY2",
        "NewYorkTMY2",
        "NewcastleEWY",
        "NorfolkTMY2",
        "NorthBendTMY2",
        "NorwichEWY",
        "OAKLAND METRO AP",
        "OXNARD AP",
        "OostendeIWEC",
        "OsakaIWEC",
        "OsloIWEC",
        "Ottawa ON CWEC",
        "PALM SPRINGS IAP",
        "PALM SPRINGS THERMAL AP",
        "PALMDALE AP",
        "PALO ALTO AP",
        "PASO ROBLES MUNI AP",
        "MANILA",
        "POINT MUGU NF",
        "PORTERVILLE(AWOS)",
        "PalermoIWEC",
        "PalmBeachTMY2",
        "PalmaIWEC",
        "ParisOrlyIWEC",
        "PhiladelphiaTMY2",
        "PhoenixTMY2",
        "PisaIWEC",
        "PocatelloTMY2",
        "PortHedlandIWEC",
        "PortlandTM2",
        "PortoIWEC",
        "Potenza IGDG",
        "PragueWYEC",
        "Pretoria Forum 19",
        "ProvidenceTMY2",
        "RED BLUFF MUNI AP",
        "REDDING MUNI AP",
        "MARCH AFB",
        "RIVERSIDE MUNI",
        "RaleighTM2",
        "Rockford TMY2",
        "RomeIWEC",
        "SACRAMENTO EXECUTIVE AP",
        "SACRAMENTO METRO AP",
        "SALINAS MUNI AP",
        "SAN CARLOS AP",
        "SAN CLEMENTE IS NAAS",
        "SAN DIEGO GILLESPIE",
        "SAN DIEGO LINDBERGH FIEL",
        "SAN DIEGO MONTGOMER",
        "SAN DIEGO NORTH ISLAND N",
        "SAN FRANCISCO IAP",
        "SAN JOSE IAP",
        "SAN JOSE REID HILLV",
        "SAN LUIS CO RGNL",
        "SAN NICHOLAS ISLAND",
        "SANDBERG",
        "SANTA ANA JOHN WAYNE AP",
        "SANTA BARBARA MUNI AP",
        "SANTA MARIA PUBLIC AP",
        "SANTA MONICA MUNI",
        "SANTA ROSA(AWOS)",
        "LAKE TAHOE",
        "STOCKTON METRO AP",
        "Salem TMY2",
        "SaltLakeCityTMY2",
        "SanDiegoTMY2",
        "SanFranciscoTMY2",
        "SanJuanTMY2",
        "SantanderIWEC",
        "SapporoIWEC",
        "Saskatoon SK CWEC",
        "ScottsbluffTMY2",
        "SeattleTMY2",
        "SevillaIWEC",
        "ShanghaiIWEC",
        "SheffieldEWY",
        "ShenyangIWEC",
        "SheridanTMY2",
        "ShimonosekiIWEC",
        "SingaporeIWEC",
        "SiouxFallsTMY2",
        "Smithers BC CWEC",
        "SpokaneTMY2",
        "SpringfieldTMY2",
        "StHubertIWEC",
        "StPetersburg IWEC",
        "StockholmIWEC",
        "Summerland BC CWEC",
        "SydneyIWEC",
        "TORRANCE MUNI AP",
        "TRUCKEE TAHOE",
        "TWENTYNINE PALMS",
        "TaipeiIWEC",
        "TallahasseeTMY2",
        "TampaTMY2",
        "Taranto IGDG",
        "ThessalonikiIWEC",
        "TokyoHyakuriIWEC",
        "TopekaTMY2",
        "TorinoIWEC",
        "Toronto ON CWEC",
        "TosashimizuIWEC",
        "TraverseCity TMY2",
        "TripoliIWEC",
        "TulsaTMY2",
        "UKIAH MUNI AP",
        "Denver Intl Ap",
        "Atlanta Hartsfield Intl Ap",
        "Chicago Ohare Intl Ap",
        "New York Central Prk Obs Belv",
        "Bellingham Intl Ap",
        "Upington 19",
        "UrumqiIWEC",
        "VAN NUYS AP",
        "VANDENBERG AFB",
        "VISALIA MUNI(AWOS)",
        "ValenciaIWEC",
        "Vancouver BC CWEC",
        "VeniceIWEC",
        "VeracruzIWEC",
        "VicenzaIGDG",
        "Victoria BC CWEC",
        "WarsawIWEC",
        "WashingtonTMY2",
        "WellingtonIWEC",
        "Winnipeg MB CWEC",
        "YUBA CO"
      ]
    }
  },
  "ASHRAE Standards": {
    "ASHRAE Climate Zones": {
      "Standard": [
        "ASHRAE CZ 1A",
        "ASHRAE CZ 1B",
        "ASHRAE CZ 2A",
        "ASHRAE CZ 2B",
        "ASHRAE CZ 3A",
        "ASHRAE CZ 3B",
        "ASHRAE CZ 3C",
        "ASHRAE CZ 4A TMY",
        "ASHRAE CZ 4B",
        "ASHRAE CZ 4C",
        "ASHRAE CZ 5A",
        "ASHRAE CZ 5B",
        "ASHRAE CZ 5C",
        "ASHRAE CZ 6A",
        "ASHRAE CZ 6B",
        "ASHRAE CZ 7",
        "ASHRAE CZ 8",
        "ASHRAE CZ 1A 2050",
        "ASHRAE CZ 1B 2050",
        "ASHRAE CZ 2A 2050",
        "ASHRAE CZ 2B 2050",
        "ASHRAE CZ 3A 2050",
        "ASHRAE CZ 3B 2050",
        "ASHRAE CZ 3C 2050",
        "ASHRAE CZ 4A 2050",
        "ASHRAE CZ 4B 2050",
        "ASHRAE CZ 4C 2050",
        "ASHRAE CZ 5A 2050",
        "ASHRAE CZ 5B 2050",
        "ASHRAE CZ 5C 2050",
        "ASHRAE CZ 6A 2050",
        "ASHRAE CZ 6B 2050",
        "ASHRAE CZ 7 2050",
        "ASHRAE CZ 8 2050",
        "ASHRAE CZ 1A 2080",
        "ASHRAE CZ 1B 2080",
        "ASHRAE CZ 2A 2080",
        "ASHRAE CZ 2B 2080",
        "ASHRAE CZ 3A 2080",
        "ASHRAE CZ 3B 2080",
        "ASHRAE CZ 3C 2080",
        "ASHRAE CZ 4A 2080",
        "ASHRAE CZ 4B 2080",
        "ASHRAE CZ 4C 2080",
        "ASHRAE CZ 5A 2080",
        "ASHRAE CZ 5B 2080",
        "ASHRAE CZ 5C 2080",
        "ASHRAE CZ 6A 2080",
        "ASHRAE CZ 6B 2080",
        "ASHRAE CZ 7 2080",
        "ASHRAE CZ 8 2080"
      ]
    }
  },
  "North America": {
    "United States": {
      "": [
        "ALTURAS",
        "ARCATA AP",
        "BAKERSFIELD MEADOWS FIEL",
        "BISHOP AP",
        "BLUE CANYON AP",
        "BLYTHE RIVERSIDE CO AP",
        "BURBANK GLENDALE PASADEN",
        "CAMARILLO(AWOS)",
        "CAMP PENDLETON MCAS",
        "CARLSBAD MCCLELLAN",
        "CA ARCATA AP",
        "CA BLUE CANYON AP",
        "CA BURBANK GLNDLE PASAD",
        "CA FRESNO YOSEMITE IAP",
        "CA FULLERTON MUNI AP",
        "CA OAKLAND METRO AP",
        "CA PALM SPRINGS IAP",
        "CA PALMDALE AP",
        "CA RED BLUFF MUNI AP",
        "CA RIVERSIDE MUNI",
        "CA SACRAMENTO EXECUTIVE",
        "CA SAN DIEGO LINDBERGH F",
        "CA SAN JOSE REID HILLV",
        "CA SANTA MARIA PUBLIC AP",
        "CA SANTA ROSA(AWOS)",
        "CA TORRANCE MUNI AP",
        "CHINA LAKE NAF",
        "CHINO AP",
        "CONCORD BUCHANAN FIELD",
        "CRESCENT CITY FAA AP",
        "DAGGETT BARSTOW DAGGETT",
        "EDWARDS AFB",
        "EL CENTRO NAF",
        "EUREKA",
        "TRAVIS FLD AFB",
        "FRESNO YOSEMITE IAP",
        "FULLERTON MUNICIPAL",
        "JACK NORTHROP FLD H",
        "HAYWARD AIR TERM",
        "IMPERIAL BEACH REAM FIEL",
        "IMPERIAL",
        "INYOKERN",
        "LANCASTER GEN WM FOX FIE",
        "LEMOORE REEVES NAS",
        "LIVERMORE MUNICIPAL",
        "LOMPOC(AWOS)",
        "LONG BEACH DAUGHERTY FLD",
        "LOS ALAMITOS AAF",
        "LOS ANGELES DOWNTOWN USC",
        "LOS ANGELES IAP",
        "BEALE AFB",
        "MERCED MUNI MACREADY",
        "MODESTO CITY CO AP",
        "MOJAVE",
        "MONTAGUE SISKIYOU CO AP",
        "MONTEREY NAF",
        "MOUNT SHASTA",
        "NAPA CO",
        "NEEDLES AP",
        "OAKLAND METRO AP",
        "OXNARD AP",
        "PALM SPRINGS IAP",
        "PALM SPRINGS THERMAL AP",
        "PALMDALE AP",
        "PALO ALTO AP",
        "PASO ROBLES MUNI AP",
        "POINT MUGU NF",
        "PORTERVILLE(AWOS)",
        "RED BLUFF MUNI AP",
        "REDDING MUNI AP",
        "MARCH AFB",
        "RIVERSIDE MUNI",
        "SACRAMENTO EXECUTIVE AP",
        "SACRAMENTO METRO AP",
        "SALINAS MUNI AP",
        "SAN CARLOS AP",
        "SAN CLEMENTE IS NAAS",
        "SAN DIEGO GILLESPIE",
        "SAN DIEGO LINDBERGH FIEL",
        "SAN DIEGO MONTGOMER",
        "SAN DIEGO NORTH ISLAND N",
        "SAN FRANCISCO IAP",
        "SAN JOSE IAP",
        "SAN JOSE REID HILLV",
        "SAN LUIS CO RGNL",
        "SAN NICHOLAS ISLAND",
        "SANDBERG",
        "SANTA ANA JOHN WAYNE AP",
        "SANTA BARBARA MUNI AP",
        "SANTA MARIA PUBLIC AP",
        "SANTA MONICA MUNI",
        "SANTA ROSA(AWOS)",
        "LAKE TAHOE",
        "STOCKTON METRO AP",
        "TORRANCE MUNI AP",
        "TRUCKEE TAHOE",
        "TWENTYNINE PALMS",
        "UKIAH MUNI AP",
        "VAN NUYS AP",
        "VANDENBERG AFB",
        "VISALIA MUNI(AWOS)",
        "YUBA CO"
      ],
      "General": [
        "AlbanyTMY2",
        "AlbuquerqueTMY2",
        "AmarilloTMY2",
        "AshevilleTMY2",
        "AtlantaTMY2",
        "Baltimore TMY2",
        "BarrowTMY2",
        "Boise TMY2",
        "BostonTMY2",
        "Burlington TMY2",
        "CaribouTMY2",
        "ChicagoMidwayTMY",
        "ChicagoOHareTMY2",
        "ClevelandTMY2",
        "ColumbusTMY2",
        "CutBankTMY2",
        "DaytonTMY2",
        "DenverStapletonTMY",
        "DetroitTMY",
        "DuluthTMY2",
        "EvansvilleTMY2",
        "Fairbanks TMY2",
        "FargoTMY2",
        "FlagstaffTMY2",
        "FortWorthTMY2",
        "FresnoTMY2",
        "GrandRapidsTMY2",
        "Helena TMY2",
        "HoustonTMY2",
        "Juneau TMY",
        "KansasCityTMY2",
        "LaredoTMY",
        "LasVegasTMY2",
        "LewistownTMY2",
        "LittleRockTMY2",
        "LosAngelesTMY2",
        "LouisvilleTMY2",
        "LynchburgTMY2",
        "MadisonTMY2",
        "Memphis TMY2",
        "MiamiTMY2",
        "Minneapolis TMY2",
        "MuskegonTMY2",
        "Nashville TMY2",
        "NewYorkTMY2",
        "NorfolkTMY2",
        "NorthBendTMY2",
        "PalmBeachTMY2",
        "PhiladelphiaTMY2",
        "PhoenixTMY2",
        "PocatelloTMY2",
        "ProvidenceTMY2",
        "Rockford TMY2",
        "Salem TMY2",
        "SaltLakeCityTMY2",
        "SanDiegoTMY2",
        "SanFranciscoTMY2",
        "SanJuanTMY2",
        "ScottsbluffTMY2",
        "SeattleTMY2",
        "SheridanTMY2",
        "SiouxFallsTMY2",
        "SpokaneTMY2",
        "SpringfieldTMY2",
        "TallahasseeTMY2",
        "TampaTMY2",
        "TopekaTMY2",
        "TraverseCity TMY2",
        "TulsaTMY2",
        "WashingtonTMY2"
      ],
      "ON": [
        "Kenora.AP"
      ],
      "CA": [
        "CA ARCATA AP",
        "CA BLUE CANYON AP",
        "CA BURBANK GLNDLE PASAD AP",
        "CA FRESNO YOSEMITE IAP",
        "CA FULLERTON MUNI AP",
        "CA LOS ANGELES IAP",
        "CA OAKLAND METRO AP",
        "CA PALM SPRINGS IAP",
        "CA PALMDALE AP",
        "CA PASO ROBLES MUNI AP",
        "CA RED BLUFF MUNI AP",
        "CA RIVERSIDE MUNI",
        "CA SACRAMENTO EXECUTIVE AP",
        "CA SAN DIEGO LINDBERGH FIE",
        "CA SANTA MARIA PUBLIC AP",
        "CA SANTA ROSA(AWOS)"
      ],
      "CO": [
        "Denver Intl Ap"
      ],
      "GA": [
        "Atlanta Hartsfield Intl Ap"
      ],
      "IL": [
        "Chicago Ohare Intl Ap"
      ],
      "NY": [
        "New York Central Prk Obs Belv"
      ],
      "WA": [
        "Bellingham Intl Ap"
      ]
    },
    "Canada": {
      "General": [
        "Abbotsford BC CWEC",
        "Calgary AB CWEC",
        "Edmonton AB CWEC",
        "Kamloops BC CWEC",
        "Montreal QC CWEC",
        "Ottawa ON CWEC",
        "Saskatoon SK CWEC",
        "Smithers BC CWEC",
        "Summerland BC CWEC",
        "Toronto ON CWEC",
        "Vancouver BC CWEC",
        "Victoria BC CWEC",
        "Winnipeg MB CWEC"
      ],
      "": [
        "MB WINNIPEG IAP"
      ]
    }
  },
  "Asia Pacific": {
    "Australia": {
      "": [
        "CANBERRA",
        "BRISBANE",
        "MELBOURNE",
        "PERTH"
      ],
      "NSW": [
        "Mascot Sydney Airport"
      ]
    },
    "China": {
      "General": [
        "BeijingIWEC",
        "GuangzhouIWEC",
        "HarbinIWEC",
        "ShanghaiIWEC",
        "ShenyangIWEC"
      ],
      "SAR": [
        "HONG KONG"
      ]
    },
    "India": {
      "Karnataka": [
        "Bangalore"
      ],
      "": [
        "CHENNAI",
        "NEW DELHI"
      ]
    },
    "New Zealand": {
      "Auckland": [
        "Auckland"
      ],
      "Bay of Plenty": [
        "Rotorua",
        "Tauranga"
      ],
      "Canterbury": [
        "Christchurch"
      ],
      "Central Otago": [
        "Lauder"
      ],
      "Hawkes Bay": [
        "Napier"
      ],
      "Manawatu": [
        "Paraparaumu"
      ],
      "Marlborough": [
        "Nelson"
      ],
      "Northland": [
        "Kaitaia"
      ],
      "Otago": [
        "Dunedin"
      ],
      "Lakes": [
        "Queenstown"
      ],
      "Southland": [
        "Invercargill"
      ],
      "Taranaki": [
        "New Plymouth"
      ],
      "Taupo": [
        "Turangi"
      ],
      "Waikato": [
        "Hamilton"
      ],
      "Wairarapa": [
        "Masterton"
      ],
      "Wellington": [
        "Wellington"
      ],
      "West Coast": [
        "Hokitika"
      ]
    }
  },
  "Europe": {
    "United Kingdom": {
      "General": [
        "AberdeenEWY",
        "AberporthEWY",
        "AldergroveEWY",
        "BirminghamEWY",
        "BristolEWY",
        "CamborneEWY",
        "DundeeEWY",
        "EskdalemuirEWY",
        "GlasgowEWY",
        "HeathrowEWY",
        "Kew67",
        "KewEWY",
        "ManchesterEWY",
        "NewcastleEWY",
        "NorwichEWY",
        "PragueWYEC",
        "SheffieldEWY"
      ]
    },
    "Spain": {
      "General": [
        "BarcelonaIWEC",
        "MadridIWEC",
        "PalmaIWEC",
        "SantanderIWEC",
        "SevillaIWEC",
        "ValenciaIWEC"
      ]
    },
    "Italy": {
      "General": [
        "Bari IGDG",
        "BrindisiIWEC",
        "Gioia del Colle IGDG",
        "MessinaIWEC",
        "MilanIWEC",
        "NaplesIWEC",
        "PalermoIWEC",
        "PisaIWEC",
        "Potenza IGDG",
        "RomeIWEC",
        "Taranto IGDG",
        "TorinoIWEC",
        "VeniceIWEC",
        "VicenzaIGDG"
      ]
    },
    "Germany": {
      "General": [
        "BerlinIWEC",
        "M\u00fcnchenIWEC"
      ]
    },
    "France": {
      "": [
        "LYON",
        "NANTES"
      ],
      "General": [
        "MarseilleIWEC",
        "NancyIWEC",
        "ParisOrlyIWEC"
      ]
    },
    "Austria": {
      "General": [
        "GrazIWEC",
        "InnsbruckIWEC"
      ]
    }
  },
  "Other Regions": {
    "International": {
      "General": [
        "AbuDhabiIWEC",
        "AcapulcoIWEC",
        "AlgiersIWEC",
        "AmsterdamIWEC",
        "AndravidaIWEC",
        "AnkaraIWEC",
        "AthensIWEC",
        "Auckland71",
        "AucklandIWEC",
        "BangkokIWEC",
        "BergenIWEC",
        "Brisbane IWEC",
        "BrusselsIWEC",
        "CairoIWEC",
        "CopenhagenIWEC",
        "DamascusIWEC",
        "Dublin89",
        "DublinIWEC",
        "EriePA TRY2",
        "HanoiIWEC",
        "HelsinkiIWEC",
        "Hrow9697",
        "Istanbul IWEC",
        "Jerusalem IWEC",
        "KagoshimaIWEC",
        "KolkataIWEC",
        "KualaLumpurIWEC",
        "KuchingIWEC",
        "KunmingIWEC",
        "Kuwait KISR",
        "LanzhouIWEC",
        "LarnacaWYEC",
        "MacauIWEC",
        "MatsumotoIWEC",
        "MelbourneIWEC",
        "MexicoCityIWEC",
        "MumbaiIWEC",
        "NadiIWEC",
        "NagoyaIWEC",
        "Nanjing CSWD",
        "Nanjing CTYW",
        "OostendeIWEC",
        "OsakaIWEC",
        "OsloIWEC",
        "PortHedlandIWEC",
        "PortlandTM2",
        "PortoIWEC",
        "RaleighTM2",
        "SapporoIWEC",
        "ShimonosekiIWEC",
        "SingaporeIWEC",
        "StHubertIWEC",
        "StPetersburg IWEC",
        "StockholmIWEC",
        "SydneyIWEC",
        "TaipeiIWEC",
        "ThessalonikiIWEC",
        "TokyoHyakuriIWEC",
        "TosashimizuIWEC",
        "TripoliIWEC",
        "UrumqiIWEC",
        "VeracruzIWEC",
        "WarsawIWEC",
        "WellingtonIWEC"
      ]
    },
    "GIB": {
      "GI": [
        "Gibraltar.Intl.AP"
      ]
    },
    "PHL": {
      "": [
        "MANILA"
      ]
    }
  },
  "Middle East & Africa": {
    "South Africa": {
      "": [
        "Cape Town 19",
        "Durban 19",
        "Johannesburg/Jan 19",
        "Beitbridge 19",
        "Pretoria Forum 19",
        "Upington 19"
      ],
      "General": [
        "JohannesburgIWEC"
      ]
    }
  }
};
