"use client";

import type { AnalysisRow, ScenarioOutputs } from "@/lib/calc-engine/types";
import type { ScenarioInputsPayload } from "@/lib/calc-engine/request";
import { generateAnalysisWriteup } from "@/lib/writeup-generator";
import { Sparkles, Award, TrendingUp, CheckCircle2, ShieldCheck, DollarSign } from "lucide-react";

interface AnalysisChartsProps {
  analysis: AnalysisRow[];
  scenarios: ScenarioOutputs[];
  payloads?: ScenarioInputsPayload[];
}

export function AnalysisCharts({ analysis, scenarios, payloads = [] }: AnalysisChartsProps) {
  if (!analysis || analysis.length === 0 || !scenarios || scenarios.length === 0) {
    return null;
  }

  const writeup = generateAnalysisWriteup(analysis, scenarios, payloads);

  // Stage colors matching design requirements
  const PREHEAT_COLOR = "#3b52c5"; // Indigo blue
  const POSTHEAT_COLOR = "#ed8936"; // Warm Amber
  const COOLING_COLOR = "#7f9cf5"; // Periwinkle light blue
  const HUMID_COLOR = "#27ab5d"; // Vibrant Emerald Green

  // Chart 1 Math: Stacked Bar Chart for Energy Use by End-Use, by Option
  const maxTotalMwh = Math.max(...scenarios.map((s) => s.totalEnergyMwh), 100);
  const chartHeightPx = 260;

  // Y-axis grid ticks (0, 200, 400, 600, 800, 1000 MWh)
  const maxYTick = Math.max(1000, Math.ceil(maxTotalMwh / 200) * 200);
  const yTicks = [0, 200, 400, 600, 800, maxYTick];

  // Chart 2 Math: Simple Payback by Option (Horizontal Bar Chart)
  const optionAnalysisRows = analysis.slice(1);
  const paybackMaxYears = 16;

  // Chart 3 Math: Annual Operational Cost by Option ($)
  const maxOpCost = Math.max(...scenarios.map((s) => s.totalOperationalCost), 1);

  return (
    <div className="mt-8 space-y-8">
      {/* 1. AUTOGENERATED WRITEUP SECTION */}
      <div className="rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50/90 via-white to-slate-50 p-6 shadow-sm">
        <div className="flex items-center justify-between border-b border-blue-100 pb-3 mb-4">
          <div className="flex items-center gap-2">
            <Sparkles className="size-5 text-[#1E4FD8]" />
            <h3 className="text-base font-extrabold text-slate-900 tracking-tight">
              Autogenerated Executive Engineering Writeup
            </h3>
          </div>
          <span className="inline-flex items-center gap-1 rounded-full bg-blue-100 px-3 py-1 text-xs font-bold text-[#1E4FD8]">
            <ShieldCheck className="size-3.5" /> Automated Analysis Engine
          </span>
        </div>

        <h4 className="text-sm font-bold text-[#1E4FD8] mb-2 flex items-center gap-1.5">
          <Award className="size-4" /> {writeup.headline}
        </h4>

        <div className="space-y-3 text-xs leading-relaxed text-slate-700">
          <p className="font-medium text-slate-800">{writeup.summaryText}</p>
          <p className="text-slate-600">{writeup.stageBreakdownText}</p>
          {writeup.financialText && (
            <p className="text-slate-600 font-medium">{writeup.financialText}</p>
          )}
          {writeup.recommendationText && (
            <div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50/90 p-3.5 text-emerald-950 font-bold flex items-start gap-2.5 shadow-2xs">
              <CheckCircle2 className="size-4 text-emerald-600 shrink-0 mt-0.5" />
              <span>{writeup.recommendationText}</span>
            </div>
          )}
        </div>
      </div>

      {/* 2. THE 3 COMPARATIVE GRAPHS SUITE */}
      <div className="space-y-6">
        <div className="border-b border-slate-200 pb-2">
          <h3 className="text-sm font-extrabold text-slate-900 uppercase tracking-wide flex items-center gap-2">
            <TrendingUp className="size-4 text-[#1E4FD8]" /> Comparative Scenario Charts
          </h3>
        </div>

        <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
          {/* CHART 1: Energy Use by End-Use, by Option (Stacked Bar Chart) */}
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between">
            <div>
              <h4 className="text-base font-extrabold text-slate-900 text-center mb-6">
                Energy Use by End-Use, by Option
              </h4>

              {/* Stacked Chart Area */}
              <div className="relative flex h-[280px] w-full items-end justify-around pl-14 pr-4 pb-8 border-b border-slate-200">
                {/* Y-axis Grid Lines & Labels */}
                <div className="absolute inset-0 flex flex-col justify-between pointer-events-none pb-8 pr-2 pl-12">
                  {[...yTicks].reverse().map((tick) => (
                    <div key={tick} className="relative w-full border-b border-slate-100 flex items-center">
                      <span className="absolute -left-12 text-[10px] font-semibold text-slate-400">
                        {tick}
                      </span>
                    </div>
                  ))}
                </div>

                {/* Y-axis Title */}
                <span className="absolute -left-8 top-1/2 -rotate-90 -translate-y-1/2 text-[10px] font-bold text-slate-500 tracking-wider">
                  Annual Energy (MWh)
                </span>

                {/* Stacked Bars */}
                {scenarios.map((s) => {
                  const totalMwh = Math.max(0, s.totalEnergyMwh);
                  const totalPct = Math.min(100, (totalMwh / maxYTick) * 100);

                  return (
                    <div key={s.scenario} className="relative flex flex-col items-center z-10 w-14 group">
                      {/* Total MWh Label on Top of Bar */}
                      <span className="mb-1.5 text-[11px] font-extrabold text-slate-900 whitespace-nowrap">
                        {Math.round(totalMwh)} MWh
                      </span>

                      {/* Stacked Bar Container */}
                      <div
                        className="w-12 rounded-t-md overflow-hidden flex flex-col-reverse shadow-xs transition-all group-hover:opacity-95 border border-slate-200/60"
                        style={{ height: `${(totalPct / 100) * chartHeightPx}px` }}
                      >
                        {/* Preheat (bottom) */}
                        {s.preheatEnergyMwh > 0 && totalMwh > 0 && (
                          <div
                            style={{ height: `${(s.preheatEnergyMwh / totalMwh) * 100}%`, backgroundColor: PREHEAT_COLOR }}
                            title={`Preheat: ${s.preheatEnergyMwh.toFixed(1)} MWh`}
                          />
                        )}
                        {/* Post-heat */}
                        {s.postHeatingEnergyMwh > 0 && totalMwh > 0 && (
                          <div
                            style={{ height: `${(s.postHeatingEnergyMwh / totalMwh) * 100}%`, backgroundColor: POSTHEAT_COLOR }}
                            title={`Post-heat: ${s.postHeatingEnergyMwh.toFixed(1)} MWh`}
                          />
                        )}
                        {/* Cooling */}
                        {s.coolingEnergyMwh > 0 && totalMwh > 0 && (
                          <div
                            style={{ height: `${(s.coolingEnergyMwh / totalMwh) * 100}%`, backgroundColor: COOLING_COLOR }}
                            title={`Cooling: ${s.coolingEnergyMwh.toFixed(1)} MWh`}
                          />
                        )}
                        {/* Humidification (top) */}
                        {s.humidificationEnergyMwh > 0 && totalMwh > 0 && (
                          <div
                            style={{ height: `${(s.humidificationEnergyMwh / totalMwh) * 100}%`, backgroundColor: HUMID_COLOR }}
                            title={`Humidification: ${s.humidificationEnergyMwh.toFixed(1)} MWh`}
                          />
                        )}
                      </div>

                      {/* X-axis Label */}
                      <span className="absolute -bottom-6 text-xs font-bold text-slate-700 whitespace-nowrap">
                        {s.scenario}
                      </span>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Legend at Bottom */}
            <div className="mt-8 flex flex-wrap items-center justify-center gap-5 text-xs font-medium text-slate-700">
              <div className="flex items-center gap-1.5">
                <span className="size-3 rounded-xs" style={{ backgroundColor: PREHEAT_COLOR }} />
                <span>Preheat</span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="size-3 rounded-xs" style={{ backgroundColor: POSTHEAT_COLOR }} />
                <span>Post-heat</span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="size-3 rounded-xs" style={{ backgroundColor: COOLING_COLOR }} />
                <span>Cooling</span>
              </div>
              <div className="flex items-center gap-1.5">
                <span className="size-3 rounded-xs" style={{ backgroundColor: HUMID_COLOR }} />
                <span>Humidification</span>
              </div>
            </div>
          </div>

          {/* CHART 2: Simple Payback by Option (Horizontal Bar Chart) */}
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm flex flex-col justify-between">
            <div>
              <h4 className="text-base font-extrabold text-slate-900 text-center mb-6">
                Simple Payback by Option
              </h4>

              {/* Chart Body Container with Clean Alignment */}
              <div className="space-y-5 pt-2 pb-4">
                {optionAnalysisRows.map((row) => {
                  const idx = analysis.findIndex((r) => r.scenario === row.scenario);
                  const payload = payloads[idx];
                  const rawTech = payload?.ervTech?.trim();

                  // Clean display name so Option 1 (Option 1) is never shown
                  const techDisplay =
                    rawTech && rawTech !== row.scenario && rawTech.toLowerCase() !== row.scenario.toLowerCase()
                      ? rawTech
                      : "";

                  const rawPayback = row.simplePaybackYears;
                  const isZeroCapEx = row.capitalCostPremium === null || Math.abs(row.capitalCostPremium) < 1;
                  const isNoPayback = rawPayback === null || rawPayback > 15;

                  // Compute bar percentage (minimum 8% width so 0.0 yrs bar is visually clear)
                  let barPct = 8;
                  let barBg = HUMID_COLOR; // Green for fast/immediate payback
                  let badgeText = "0.0 yrs (Immediate)";

                  if (isNoPayback || (rawPayback && rawPayback > 8)) {
                    barBg = "#e53e3e"; // Red for no payback
                    barPct = 100;
                    badgeText = "100+ yrs (no payback)";
                  } else if (rawPayback && rawPayback > 0.05 && !isZeroCapEx) {
                    const val = Math.min(rawPayback, 15);
                    barPct = Math.max(8, (val / paybackMaxYears) * 100);
                    barBg = rawPayback > 3.5 ? POSTHEAT_COLOR : HUMID_COLOR;
                    badgeText = `${rawPayback.toFixed(1)} yrs`;
                  }

                  return (
                    <div key={row.scenario} className="flex items-center gap-3">
                      {/* Scenario & Tech Label (left column) */}
                      <div className="w-28 shrink-0 text-right text-xs leading-snug">
                        <span className="font-extrabold text-slate-900 block truncate">{row.scenario}</span>
                        {techDisplay && (
                          <span className="text-[11px] font-medium text-slate-500 block truncate">
                            {techDisplay}
                          </span>
                        )}
                      </div>

                      {/* Bar & Badge Area */}
                      <div className="flex-1 flex items-center gap-2.5 min-w-0">
                        <div
                          className="h-7 rounded-r-md transition-all duration-500 shadow-2xs shrink-0 flex items-center justify-end px-2"
                          style={{ width: `${barPct}%`, backgroundColor: barBg }}
                        />
                        <span className="text-xs font-bold text-slate-900 whitespace-nowrap shrink-0">
                          {badgeText}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* X-axis Ticks & Label Footer */}
            <div className="pt-3 border-t border-slate-100">
              <div className="flex justify-between pl-32 pr-12 text-[10px] font-bold text-slate-400 mb-1">
                {[0, 2, 4, 6, 8, 10, 12, 14, 16].map((tick) => (
                  <span key={tick}>{tick}</span>
                ))}
              </div>
              <div className="text-center text-xs font-bold text-slate-500">
                Simple Payback (years)
              </div>
            </div>
          </div>

          {/* CHART 3: Annual Operational Cost by Option ($) */}
          <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2">
            <h4 className="text-base font-extrabold text-slate-900 text-center mb-6 flex items-center justify-center gap-2">
              <DollarSign className="size-5 text-emerald-600" /> Annual Operational Cost by Option ($/yr)
            </h4>

            <div className="space-y-4 max-w-3xl mx-auto">
              {scenarios.map((s, i) => {
                const cost = s.totalOperationalCost;
                const pct = Math.max(4, (cost / maxOpCost) * 100);
                const isBase = s.scenario === "BaseCase";
                const payload = payloads[i];
                const techName = payload?.ervTech && payload.ervTech !== s.scenario ? payload.ervTech : "";

                return (
                  <div key={s.scenario} className="space-y-1">
                    <div className="flex justify-between text-xs font-bold text-slate-800">
                      <span>{s.scenario} {techName ? `(${techName})` : ""}</span>
                      <span className="font-mono text-slate-900">${Math.round(cost).toLocaleString("en-US")}</span>
                    </div>
                    <div className="h-5 w-full rounded-full bg-slate-100 overflow-hidden flex items-center p-0.5 border border-slate-200">
                      <div
                        className="h-full rounded-full transition-all duration-700"
                        style={{
                          width: `${pct}%`,
                          backgroundColor: isBase ? "#64748b" : "#10b981",
                        }}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
